### ISSUE TITLE
div header_user is displayed not at top. 

### ISSUE THREAD

**Issue by tspreche** [tpeigne/simpleresponsivetheme#1]
hi tpeigne

div header_user is displayed not at top. instead its on third positon after the logo and the main navigation.

is this currently wrong or did i made something wrong with unhooking all modules while installing. i removed all frontend modules.

thanks
please feedback if you know thats a common problem.

**Comment by tpeigne** [comment]
Hi tspreche,

Your problem is a module position problem. The module responsivetopbar is under the module responsivelinks. In the administration, in module positions section, switch the position between the 2 modules and it will fix your problem.

See the example bellow.
![displayhome](https://f.cloud.github.com/assets/851345/705035/c1dbbbda-ddcd-11e2-831c-a4454919970c.png)
