### ISSUE TITLE
'Old' and 'new' prices of the discounted goods takes 1 more line. It leads to corrupted alignment of the goods

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#26]
How to check:
Make a valid discount for 1 product. Old price: 120 000 EURO. New price: 100 000 EURO.
Go to this products' category in the front office.

Result:
Prices now take 2 lines instead of 1. Therfore, 'Add to cart' button for this product goes lower than for the other products.

Suggestion: Not to display currency 2 times, e.g.:

Now:          100 000 EURO (red) 120 000 EURO (striked)
Should be: 120 000(striked) 100 000 EURO(red)

What do you think?

**Comment by tpeigne** [comment]
Hello Hoogie,

I think that this is not a theme issue. Because product prices display have to be adapted for every shop. I try to develop a generic theme for all shops and can adapt the theme for everyone. I don't know which shop can have product price more than 100 000!

So i think that you have to adapt the price display for your own shop if you have products that cost more than 100 000€.

Thanks,
tpeigne

**Comment by Hoggie** [comment]
Please remember that there are different currencies worldwide beside Euro and USD, and e.g. there are currencies with rate 1 EUR - 10 000 local money units. So, if the price of some product will take 6 symbols or more, the view will be corrupted.

I just made a suggestion that will exclude all further potential problems for any user all around the world. I believe it's a good way of developing.

Moreover, I think that have a little reserve of symbols in the line is a good slant in programming.

And one more thing: I don't think that mentioning currency 2 times in the line is normal. It distracts the buyer from the main thing that should be in focus: old and new price.

Have a nice weekend btw :)
