### ISSUE TITLE
No link to return to Mobile view after switching to Full View from tablet

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#8]
If visitor customer comes from a tablet or smartphone browser, then switched to Full View (clicked 'Browse the full site') - no link to return to mobile site then.

Or I just cannot find the link? :)

Thanks

**Comment by tpeigne** [comment]
Hello Hoggie,

With the responsive design, you don't have to use a custom mobile theme. Because your responsive design is adaptable for mobiles or tablets. So why do you want to click on 'Browse the full site' ?

I think that you have enable the mobile theme in your theme configuration. With a responsive theme, you don't have to enable the mobile theme.

Thanks,
tpeigne

**Comment by Hoggie** [comment]
Absolutely. You are right.
